apiVersion: v1
kind: Pod
metadata:
  name: springboot-ia-test
  labels:
    zone: prod
    version: v1
spec:
  containers:
   - name: springboot-ia-test   
     image: federicomartinlara1976/springboot-ia-test:v3
